### ISSUE TITLE
Module Error when executing [ node app.js ] 

### ISSUE THREAD

**Issue by geopayme** [thebitcoincoop/coinos#28]
root@BTC:~/coinos# node app.js

module.js:340
    throw err;
          ^
Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/coinos/app.js:16:12)
    at Object.<anonymous> (/root/coinos/app.js:161:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by geopayme** [comment]
The error was fixed.

The installation does not create a  config directory. 

Solution:

Create the config subdirectory in the coinos path
then copy the config.js.sample file in the ./config directory and rename it to config.js
